### ISSUE TITLE
Segmentation fault when torchscripting

### ISSUE THREAD

**Issue by frostedoyster** [lab-cosmo/metatensor#349]
Getting a segmentation fault in the latest version of `torch_spex`, `torchscript` branch.

`gdb` output:
```
#0  0x0000000064c81e20 in ?? ()
#1  0x00007fffd674adc3 in metatensor::DataArrayBase::to_mts_array_t(std::unique_ptr<metatensor::DataArrayBase, std::default_delete<metatensor::DataArrayBase> >)::{lambda(void const*, unsigned long*)#2}::_FUN(void const*, unsigned long*) ()
   from /home/filippo/.local/lib/python3.8/site-packages/metatensor/torch/lib/libmetatensor_torch.so
#2  0x00007fffd67475c5 in metatensor_torch::TensorBlockHolder::values() () from /home/filippo/.local/lib/python3.8/site-packages/metatensor/torch/lib/libmetatensor_torch.so
#3  0x00007fffd67949d6 in std::_Function_handler<void (std::vector<c10::IValue, std::allocator<c10::IValue> >&), torch::class_<metatensor_torch::TensorBlockHolder>::defineMethod<torch::detail::WrapMethod<at::Tensor (metatensor_torch::TensorBlockHolder::*)()> >(std::string, torch::detail::WrapMethod<at::Tensor (metatensor_torch::TensorBlockHolder::*)()>, std::string, std::initializer_list<torch::arg>)::{lambda(std::vector<c10::IValue, std::allocator<c10::IValue> >&)#1}>::_M_invoke(std::_Any_data const&, std::vector<c10::IValue, std::allocator<c10::IValue> >&) () from /home/filippo/.local/lib/python3.8/site-packages/metatensor/torch/lib/libmetatensor_torch.so
#4  0x00007fffd676856d in torch::jit::BuiltinOpFunction::call(std::vector<c10::IValue, std::allocator<c10::IValue> >&, c10::optional<unsigned long>, c10::function_ref<void (torch::jit::Code const&)>) ()
   from /home/filippo/.local/lib/python3.8/site-packages/metatensor/torch/lib/libmetatensor_torch.so
#5  0x00007fff7bffddd0 in torch::jit::InterpreterStateImpl::callFunction(torch::jit::Function&, std::vector<c10::IValue, std::allocator<c10::IValue> >&, c10::optional<unsigned long>, bool) ()
   from /home/filippo/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#6  0x00007fff7c01157f in torch::jit::InterpreterStateImpl::runImpl(std::vector<c10::IValue, std::allocator<c10::IValue> >&) () from /home/filippo/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#7  0x00007fff7bffd4cf in torch::jit::InterpreterState::run(std::vector<c10::IValue, std::allocator<c10::IValue> >&) () from /home/filippo/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#8  0x00007fff7bfee29a in torch::jit::GraphExecutorImplBase::run(std::vector<c10::IValue, std::allocator<c10::IValue> >&) () from /home/filippo/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so
#9  0x00007fff9095a4be in torch::jit::runAndInsertCall(torch::jit::Function&, torch::jit::tuple_slice const&, pybind11::kwargs const&, c10::optional<c10::IValue>, std::function<torch::jit::Value* (torch::jit::Graph&, torch::jit::MatchedSchema const&)> const&) () from /home/filippo/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#10 0x00007fff90a2c523 in torch::jit::invokeScriptMethodFromPython(torch::jit::Method&, torch::jit::tuple_slice const&, pybind11::kwargs const&) () from /home/filippo/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#11 0x00007fff909ee5d1 in pybind11::cpp_function::initialize<torch::jit::initJitScriptBindings(_object*)::{lambda(pybind11::args, pybind11::kwargs)#68}, pybind11::object, pybind11::args, pybind11::kwargs, pybind11::name, pybind11::is_method, pybind11::sibling>(torch::jit::initJitScriptBindings(_object*)::{lambda(pybind11::args, pybind11::kwargs)#68}&&, pybind11::object (*)(pybind11::args, pybind11::kwargs), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) () from /home/filippo/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#12 0x00007fff90462050 in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) () from /home/filippo/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#13 0x00000000005f6489 in PyCFunction_Call ()
#14 0x00000000005f7056 in _PyObject_MakeTpCall ()
#15 0x000000000050b968 in ?? ()
#16 0x00000000005f5c02 in PyObject_Call ()
#17 0x000000000059d8c1 in ?? ()
#18 0x00000000005f5dfe in PyObject_Call ()
#19 0x000000000056d1fc in _PyEval_EvalFrameDefault ()
#20 0x0000000000569cea in _PyEval_EvalCodeWithName ()
#21 0x00000000005f6a13 in _PyFunction_Vectorcall ()
#22 0x000000000059d5d5 in ?? ()
```

**Comment by Luthaf** [comment]
Does this happen when running a module compiled with TorchScript?
